const USER_ROLES = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  ADMIN: "ADMIN"
};

const APPOINTMENT_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  RESCHEDULED: "RESCHEDULED"
};

const PAYMENT_MODE = {
  MANUAL: "MANUAL",
  ONLINE: "ONLINE"
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED"
};

const SLOT_STATE = {
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE: "UNAVAILABLE",
  BOOKED: "BOOKED"
};

const ACTIVE_BLOCKING_APPOINTMENT_STATUSES = [
  APPOINTMENT_STATUS.PENDING_PAYMENT,
  APPOINTMENT_STATUS.CONFIRMED,
  APPOINTMENT_STATUS.RESCHEDULED
];

const ALLOWED_PAYMENT_STATUS_TRANSITIONS = {
  [PAYMENT_STATUS.PENDING]: [PAYMENT_STATUS.PAID, PAYMENT_STATUS.FAILED, PAYMENT_STATUS.REFUNDED],
  [PAYMENT_STATUS.PAID]: [PAYMENT_STATUS.REFUNDED],
  [PAYMENT_STATUS.FAILED]: [PAYMENT_STATUS.PENDING],
  [PAYMENT_STATUS.REFUNDED]: []
};

const ALLOWED_APPOINTMENT_STATUS_TRANSITIONS = {
  [APPOINTMENT_STATUS.PENDING_PAYMENT]: [
    APPOINTMENT_STATUS.CONFIRMED,
    APPOINTMENT_STATUS.CANCELLED
  ],
  [APPOINTMENT_STATUS.CONFIRMED]: [
    APPOINTMENT_STATUS.CANCELLED,
    APPOINTMENT_STATUS.COMPLETED,
    APPOINTMENT_STATUS.REJECTED,
    APPOINTMENT_STATUS.RESCHEDULED
  ],
  [APPOINTMENT_STATUS.RESCHEDULED]: [
    APPOINTMENT_STATUS.CONFIRMED,
    APPOINTMENT_STATUS.CANCELLED
  ],
  [APPOINTMENT_STATUS.CANCELLED]: [],
  [APPOINTMENT_STATUS.COMPLETED]: [],
  [APPOINTMENT_STATUS.REJECTED]: []
};

module.exports = {
  USER_ROLES,
  APPOINTMENT_STATUS,
  PAYMENT_MODE,
  PAYMENT_STATUS,
  SLOT_STATE,
  ACTIVE_BLOCKING_APPOINTMENT_STATUSES,
  ALLOWED_PAYMENT_STATUS_TRANSITIONS,
  ALLOWED_APPOINTMENT_STATUS_TRANSITIONS
};