services:
  api-gateway:
    build:
      context: ./services/api-gateway
    ports:
      - "5000:5000"
    env_file:
      - ./services/api-gateway/.env
    depends_on:
      - auth-service
      - patient-service
      - doctor-service
      - ai-service
      - appointment-service
      - payment-service
      - telemedicine-service
      - notification-service

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/auth-service/.env

  ai-service:
    build:
      context: ./services/ai-service
    ports:
      - "5004:5004"
    env_file:
      - ./services/ai-service/.env

  telemedicine-service:
    build:
      context: ./services/telemedicine-service
    ports:
      - "5005:5005"
    env_file:
      - ./services/telemedicine-service/.env

  payment-service:
    build:
      context: ./services/payment-service
    ports:
      - "5006:5006"
    env_file:
      - ./services/payment-service/.env

  appointment-service:
    build:
      context: ./services/appointment-service
    ports:
      - "5007:5007"
    env_file:
      - ./services/appointment-service/.env

  doctor-service:
    build:
      context: ./services/doctor-service
    ports:
      - "5010:5010"
    env_file:
      - ./services/doctor-service/.env

  patient-service:
    build:
      context: ./services/patient-service
    ports:
      - "5015:5015"
    env_file:
      - ./services/patient-service/.env

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "5008:5008"
    env_file:
      - ./services/notification-service/.env

  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - api-gateway